# Site settings
title: Roberto Zen
email: roberto dot zen at outlook dot com
description: >
  I am a MSc Student at University of Trento and I am an Über Tester and 
  I am working on BringTheFood which is a project by FBK’s ICT4G research unit.
footer_description: I love my mac.
baseurl: ""

twitter_username: zenzu92
github_username:  robzenn92
facebook_username: roberto.zenn92

# Build settings
markdown: kramdown
